services:
  node-app:
    # build: .
    container_name: express-node-app-container
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    depends_on: 
      # - postgres
      - mongo
      - redis
    networks:
      - app-network

  mongo:
    image: mongo:4.4
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - app-network


  redis:
    image: redis:6-alpine
    depends_on: 
      # - postgres
      - mongo
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    depends_on: 
      - node-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

# region those nodes, wrorking for back-end with nginx reverse-proxy.
  # node-app-1:
  #   # build: .
  #   container_name: express-node-app-container-1
  #   ports:
  #     - "4001:4000"
  #   env_file:
  #     - ./.env
  #   depends_on: 
  #     - postgres
  #     - redis
  #   networks:
  #     - app-network

  # node-app-2:
  #   # build: .
  #   container_name: express-node-app-container-2
  #   ports:
  #     - "4002:4000"
  #   env_file:
  #     - ./.env
  #   depends_on: 
  #     - postgres
  #     - redis
  #   networks:
  #     - app-network

  # node-app-3:
  #   # build: .
  #   container_name: express-node-app-container-3
  #   ports:
  #     - "4003:4000"
  #   env_file:
  #     - ./.env
  #   depends_on: 
  #     - postgres
  #     - redis
  #   networks:
  #     - app-network

  # postgres:
  #   image: postgres:15-alpine
  #   container_name: postgres_db
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgrespassword
  #     POSTGRES_DB: mydatabase
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network


volumes:
  mongo-db:
  postgres_data:

networks:
  app-network:
    driver: bridge